const cn = {
	locale:"cn",
	language:"Chinese",
	change_language:"click here to english version",
	menu_item1:"网页设计",
	menu_item2:"个人简历",
	menu_item3:"相关技能/项目",
	menu_item4:"联系方式",
	brief_intro_web_design:"我坚信合理的工作流程能产生更好的客户体验",
	brief_intro_resume:"相关的技术和项目展示",
	brief_intro_home:"欢迎来到Rick的个人网页，希望能帮助各位更好的了解我:)",
	description:`我叫Rick,目前从事网页开发工作。
				掌握web基础开发（HTML/CSS/Javascript）技能，有一年的wordpress和服务器后台(mySQL,php)管理的经验,代码规范良好，熟悉掌握github的使用，可单独/团队合作，有很好的抗压能力，积极完成领导布置的任务。*
				目前寻找兼职中，期待能有与您有一同共事的机会。`,
	sp_link:"详细的技能列表请查看",
	sub_title:"叫我Rick就好",
	webpage_title:"工作流程",
	working_step1:"通过会面理解客户需求，定制专属方案",
	working_step2:"根据会议记录的客户需求制作网站，时间取决于实际情况",
	working_step3:"客户审查通过后交付内容,本次服务结束，根据协议转入售后服务流程*",
	working_comment:"*默认售后服务时间为半年，具体时长根据工作内容的不同而有所变化",
	resume_title:"相关技能（前端）",
	skill_description:"一直对前段技术有着浓厚的兴趣，有幸能在第一份工作中实践这些技能（HTML, CSS, Javascript）。与此同时，我也正在努力地学习各种流行的前段技术，并这些技术融入我的工作之中",
	table_skill_title:"技能",
	table_skill_description_title:"掌握程度",
	table_skill_description2_title:"相关项目/Demo",
	table_skill1:"HTML",
	table_skill_description1:"编写遵循HTML5规则的HTML静态网页",
	table_skill2:"CSS",
	table_skill_description2:"熟悉css，可以根据需求对网页布局和制作各种css动画",
	table_skill3:"Javascript",
	table_skill_description3:"熟悉Javascript语法，与css同实现动态网页",
	table_skill4:"",
	table_skill_description4:"",
	table_skill5:"",
	table_skill_description5:"",
	table_skill6:"",
	table_skill_description6:"",
	resume_title:"个人简介",
	resume_content:"感谢您对我的关注，本人目前正在寻找web前端相关工作，个人简历请通过联系页面与本人取得联系后获取",
	contact_title:"感谢浏览本个人网页，以下是我的联系方式",
	contact_content:"",
}
export default cn;
