const en = {
	locale:"en",
	language:"English",
	change_language:"点击这里转换为中文版",
	menu_item1:"web design",
	menu_item2:"resume",
	menu_item3:"skill & project",
	menu_item4:"contact",
	brief_intro_web_design:"this how I will help for build your website",
	brief_intro_resume:"relative skill will present below",
	brief_intro_home:"welcome to rick's prosonal website, wish your have a nice day:)",
	description:`I'm Rick, now I working as a web developer.
I am able to develop a dynamic webpage with JavaScript, html5/css3 independently. experience with website administrator. can do all the daily administration include Mysql, PHP backend. know how to use Github, good working attitude and well communication skill with the team member. undertaking high-pressure pressure. 
looking for the part-time job now, wish has chances working with you.
		`,
	sp_link:"the skill specify is on the ",
	sub_title:"just call me Rick.",
	webpage_title:"Design process",
	working_step1:"the first meeting will given your personal plan for you website design",
	working_step2:"according to meeting, I will spend time on designing you site and info your program from time to time.",
	working_step3:"onces your has approve my website design, this contract will be end and I will happy to help with after service*",
	working_comment:"usually I will given half year customer service for free, but it will change basic on contract.",
	resume_title:"relative skill (Front-end)",
	skill_description:"I always have interest in the front-end development, I am happy to have an change for used it on my first job. (html5, css3, and javascript). Also, I had learned some popular front-end frameworks during this time (Node.js and React). ",
	table_skill_title:"skill",
	table_skill_description_title:"skill description",
	table_skill_description2_title:"relative project",
	table_skill1:"HTML",
	table_skill_description1:"able to write pure HTML website, which follows the html5 standard",
	table_skill2:"CSS",
	table_skill_description2:"familiar with css3, can create simple animation as I need",
	table_skill3:"Javascript",
	table_skill_description3:"understand the basic of Javascript and used on the development process",
	table_skill4:"",
	table_skill_description4:"",
	table_skill5:"",
	table_skill_description5:"",
	table_skill6:"",
	table_skill_description6:"",
	resume_title:"CV",
	resume_content:"thanks for you visit. require of CV please ",
	contact_title:"talk to me? here is the way",
	contact_content:"",
}
export default en;
